### ISSUE TITLE
Error when running the exemple in the README

### ISSUE THREAD

**Issue by BasileGoussard** [CS-SI/eodag-cube#15]
**Describe the bug**
I'm trying to run the example in the README but instead of retrieving a xarray a got the following message 
```
Eodag does not support getting data from distant sources by now. Falling back to first downloading the product and then getting the data...
```

**Code To Reproduce**
By using exactly the same code as the README:
```
from eodag import EODataAccessGateway
from rasterio.crs import CRS

dag = EODataAccessGateway()
product_type = 'S2_MSI_L1C'
footprint = {'lonmin': 1, 'latmin': 43.5, 'lonmax': 2, 'latmax': 44}
start, end = '2020-06-04', '2020-06-05'
search_results, _ = dag.search(productType=product_type, geom=footprint, start=start, end=end)
data = search_results[0].get_data(
    crs=CRS.from_epsg(4326),
    resolution=0.0006,
    band="B01",
    extent=footprint
)
print(data)
```

**Output**
```
Eodag does not support getting data from distant sources by now. Falling back to first downloading the product and then getting the data...
---------------------------------------------------------------------------
UnsupportedDatasetAddressScheme           Traceback (most recent call last)
~/opt/miniconda3/envs/eodag/lib/python3.9/site-packages/eodag_cube/api/product/_product.py in get_data(self, crs, resolution, band, extent)
     79         try:
---> 80             dataset_address = self.driver.get_data_address(self, band)
     81         except UnsupportedDatasetAddressScheme:

~/opt/miniconda3/envs/eodag/lib/python3.9/site-packages/eodag_cube/api/product/drivers/sentinel2_l1c.py in get_data_address(self, eo_product, band)
     96             raise AddressNotFound
---> 97         raise UnsupportedDatasetAddressScheme(
     98             "eo product {} is accessible through a location scheme that is not yet "

UnsupportedDatasetAddressScheme: eo product EOProduct(id=S2B_MSIL1C_20200604T104619_N0209_R051_T31TCJ_20200604T125433, provider=peps) is accessible through a location scheme that is not yet supported by eodag: https
```

**Environment:**
 - Python version: `Python 3.9.5`
 - EODAG version: `eodag (Earth Observation Data Access Gateway): version 2.3.0`
 - I run : ```python -m pip install eodag-cube``` (10mn ago)

**Additional context**
If I need a specific provider I would be pleased to know which one.

Thanks again for all this work! 
That is clearly helping to democratize earth observation data
Best

**Comment by sbrunato** [comment]
@BasileGoussard thanks again for the report, and the postive feedback! 

I do not manage to reproduce this issue. Can you please run the example again with more verbosity, using:
```py
from eodag import setup_logging
setup_logging(3) # DEBUG level
```
and post the output here. Thanks

**Comment by lhcorralo** [comment]
Hello

I have also tried to run the example code and I am getting some issues, despite looking different than the ones described by @BasileGoussard 

**Describe the bug**

The example in the README does not work

**Code To Reproduce**

`from eodag import setup_logging, EODataAccessGateway
from rasterio.crs import CRS

setup_logging(3)  # DEBUG level
dag = EODataAccessGateway()
product_type = 'S2_MSI_L1C'
footprint = {'lonmin': 1, 'latmin': 43.5, 'lonmax': 2, 'latmax': 44}
start, end = '2020-06-04', '2020-06-05'
search_results, _ = dag.search(productType=product_type, geom=footprint, start=start, end=end)
data = search_results[0].get_data(
    crs=CRS.from_epsg(4326),
    resolution=0.0006,
    band="B01",
    extent=footprint
)
print(data)`

**Output**

`2021-07-22 10:21:13,216-15s eodag.config                     [INFO    ] (config           ) Loading user configuration from: C:\Users\lherreroc\.config\eodag\eodag.yml
2021-07-22 10:21:14,968-15s eodag.core                       [DEBUG   ] (core             ) Opening product types index in C:\Users\lherreroc\.config\eodag\.index
2021-07-22 10:21:15,158-15s eodag.core                       [INFO    ] (core             ) Locations configuration loaded from C:\Users\lherreroc\.config\eodag\locations.yml
2021-07-22 10:21:23,242-15s eodag.core                       [INFO    ] (core             ) Searching product type 'S2_MSI_L1C' on provider: peps
2021-07-22 10:21:23,242-15s eodag.core                       [DEBUG   ] (core             ) Using plugin class for search: QueryStringSearch
2021-07-22 10:21:23,242-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Mapping eodag product type to provider product type
2021-07-22 10:21:23,242-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Getting provider product type definition parameters for S2_MSI_L1C
2021-07-22 10:21:23,242-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Getting provider product type definition parameters for S2_MSI_L1C
2021-07-22 10:21:23,242-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Building the query string that will be used for search
2021-07-22 10:21:23,244-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Retrieving queryable metadata from metadata_mapping
2021-07-22 10:21:23,245-15s eodag.plugins.search.qssearch    [INFO    ] (qssearch         ) Sending count request: https://peps.cnes.fr/resto/api/collections/S2ST/search.json?startDate=2020-06-04&completionDate=2020-06-05&geometry=POLYGON ((1.0000 43.5000, 1.0000 44.0000, 2.0000 44.0000, 2.0000 43.5000, 1.0000 43.5000))&productType=S2MSI1C&maxRecords=1&page=1
2021-07-22 10:21:24,248-15s eodag.plugins.search.qssearch    [INFO    ] (qssearch         ) Sending search request: https://peps.cnes.fr/resto/api/collections/S2ST/search.json?startDate=2020-06-04&completionDate=2020-06-05&geometry=POLYGON ((1.0000 43.5000, 1.0000 44.0000, 2.0000 44.0000, 2.0000 43.5000, 1.0000 43.5000))&productType=S2MSI1C&maxRecords=20&page=1
2021-07-22 10:21:24,944-15s eodag.plugins.search.qssearch    [DEBUG   ] (qssearch         ) Adapting 2 plugin results to eodag product representation
2021-07-22 10:21:25,271-15s eodag.api.product                [WARNING ] (_product         ) Drivers definition seems out-of-date, please update eodag-cube
2021-07-22 10:21:25,390-15s eodag.api.product                [WARNING ] (_product         ) Drivers definition seems out-of-date, please update eodag-cube
2021-07-22 10:21:25,390-15s eodag.core                       [INFO    ] (core             ) Found 2 result(s) on provider 'peps'
Traceback (most recent call last):
  File "C:\Users\xxxxxx\Miniconda3\envs\yyyyyy\lib\site-packages\eodag_cube\api\product\_product.py", line 80, in get_data
    dataset_address = self.driver.get_data_address(self, band)
  File "C:\Users\xxxxxx\Miniconda3\envs\yyyyyy\lib\site-packages\eodag\api\product\drivers\base.py", line 35, in get_data_address
    raise NotImplementedError
NotImplementedError`

**Environment**

- Python 3.7
- eodag 2.3.1, installed with conda
- eodag-cube 0.1.2, installed with pip

**Additional context**

The driver is NoDriver, and a message telling to update the package appears.

`search_results[0].get_driver()
2021-07-22 10:25:34,111-15s eodag.api.product                [WARNING ] (_product         ) Drivers definition seems out-of-date, please update eodag-cube
<eodag.api.product.drivers.base.NoDriver object at 0x0000021496C59148>`

However, conda-cube is up to date

Thank you!!

**Comment by sbrunato** [comment]
> 2021-07-22 10:21:25,271-15s eodag.api.product                [WARNING ] (_product         ) Drivers definition seems out-of-date, please update eodag-cube

> **Environment**
> 
>     * Python 3.7
> 
>     * eodag 2.3.1, installed with conda
> 
>     * eodag-cube 0.1.2, installed with pip

Hello @lhcorralo,
please update `eodag` and `eodag-cube`. Regarding your logs, updating `eodag-cube` to `0.2.0` minimum should be enough.

**Comment by sbrunato** [comment]
@BasileGoussard, your issue may be related to missing/wrong credentials, or maybe a temporary server issue (peps had some during June & July). Did you post the full output ?
I tried running the example using the same versions as yours. 

If credentials are missing I get the following output:
```py
Eodag does not support getting data from distant sources by now. Falling back to first downloading the product and then getting the data...
Traceback (most recent call last):
  File "/opt/conda/envs/eodag/lib/python3.9/site-packages/eodag_cube/api/product/_product.py", line 80, in get_data
    dataset_address = self.driver.get_data_address(self, band)
  File "/opt/conda/envs/eodag/lib/python3.9/site-packages/eodag_cube/api/product/drivers/sentinel2_l1c.py", line 97, in get_data_address
    raise UnsupportedDatasetAddressScheme(
eodag.utils.exceptions.UnsupportedDatasetAddressScheme: eo product EOProduct(id=S2B_MSIL1C_20200604T104619_N0209_R051_T31TCJ_20200604T125433, provider=peps) is accessible through a location scheme that is not yet supported by eodag: https

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/eodag/lib/python3.9/site-packages/eodag_cube/api/product/_product.py", line 88, in get_data
    path_of_downloaded_file = self.download()
  File "/opt/conda/envs/eodag/lib/python3.9/site-packages/eodag/api/product/_product.py", line 270, in download
    self.downloader_auth.authenticate()
  File "/opt/conda/envs/eodag/lib/python3.9/site-packages/eodag/plugins/authentication/generic.py", line 29, in authenticate
    self.validate_config_credentials()
  File "/opt/conda/envs/eodag/lib/python3.9/site-packages/eodag/plugins/authentication/base.py", line 50, in validate_config_credentials
    raise MisconfiguredError(
eodag.utils.exceptions.MisconfiguredError: The following credentials are missing for provider peps: username, password
```
- Can you please run the example again with more verbosity, and post the full output: 
> ```python
> from eodag import setup_logging
> setup_logging(3) # DEBUG level
> ```

- Or update `eodag` + `eodag-cube`:
```bash
conda update eodag
# or
pip install -U eodag

pip install -U eodag-cube
```
Thanks

**Comment by BasileGoussard** [comment]
Hi @sbrunato,

Thanks for your reply.
Indeed I got a temporary issue with the peps server. 
Know the readme example is running without any trouble. 

Have a nice week-end,
Basile
