### ISSUE TITLE
Is get_data usable with S2_MSI_L2A data

### ISSUE THREAD

**Issue by Axel2017** [CS-SI/eodag-cube#32]
**Describe the bug**
I want to get specific bands from Sentinel 2 L2A using get_data function. This works fine for Sentinel  2 L1C but with L2A I get the following output

**Output**
```
Traceback (most recent call last):
  File "/home/axelwagner/eodag_test/git_issue.py", line 10, in <module>
    data = search_results[0].get_data(
  File "/home/axelwagner/.local/lib/python3.8/site-packages/eodag_cube/api/product/_product.py", line 93, in get_data
    dataset_address = self.driver.get_data_address(self, band)
  File "/home/axelwagner/.local/lib/python3.8/site-packages/eodag/api/product/drivers/base.py", line 35, in get_data_address
    raise NotImplementedError
NotImplementedError
```
**Questions
Is get_data only compatible with certain products? If get_data is not compatible with L2A is there another way I can get only part of the L2A data without downloading the entire folder

**Code To Reproduce**
```py
from eodag import EODataAccessGateway
from rasterio.crs import CRS

dag = EODataAccessGateway()
dag.set_preferred_provider(provider='creodias')
product_type = 'S2_MSI_L2A'
footprint = {'lonmin': 1, 'latmin': 43.5, 'lonmax': 2, 'latmax': 44}
start, end = '2023-03-10', '2023-03-12'
search_results, _ = dag.search(productType=product_type, geom=footprint, start=start, end=end)
data = search_results[0].get_data(
    crs=CRS.from_epsg(4326),
    resolution=0.0001,
    band="B03",
    extent=footprint
)
print(data)
```

**Comment by sbrunato** [comment]
The feature is now available through the generic driver included in [v0.3.0](https://github.com/CS-SI/eodag-cube/releases/tag/v0.3.0)
